---
title: "AoI/Field selection for satellite data based analyses"
output: html_notebook
---

Content of this script
* Analysis of metadata for available satellite imagery given AoI, timeframe, sensor, etc
* Plotting spatial frequency distribution for satellite imagery
* Further explorative analyses for potential fields to nail down the selection

```{r, setup}
# set workdir
knitr::opts_knit$set(root.dir = 'C://Users/felix/Desktop/Adv_Rs_project')
```

```{r}
# set locale
Sys.setlocale("LC_ALL", "English")
```

```{r}
# load required packages (and install them if necessary)
packages = c('fasterize', 'getSpatialData', 'leaflet', 'raster', 'rgeos', 'sf', 'sp', 'skimr', 'tidyverse')

available_packages = lapply(packages, require, character.only = T)
#install.packages(packages[!unlist(available_packages)])
#update.packages()

## check which packages are actually used
## convert to R file
# path = "..."
# document_name = "distribution_s1_austria.Rmd"
# document_name_R = paste0(unlist(strsplit(document_name, "\\."))[1], ".R")
# 
# library(NCmisc)
# knitr::purl(file.path(path, "distribution_s1_austria.Rmd"), 
#             file.path(path, document_name_R))
# list.functions.in.file(file.path(path, document_name_R), alphabetic = TRUE)
```

```{r}
# Define area of interest
austria_boundaries = file.path(getwd(), 
                               "01_data_raw", 
                               "VGD-Oesterreich_gen_50_01.04.2021", 
                               "VGD_Österreich_gen_50.shp")
Aoi = st_read(austria_boundaries) %>% 
      {as_Spatial(st_geometry(.), IDs = as.character(1:nrow(.)))} %>% 
      raster::aggregate(.)
set_aoi(Aoi)

view_aoi()
```

```{r}
# download metadata of all scenes for aoi & product type
login_CopHub(username = "fkroeber12")
records = getSentinel_records(time_range = c("2021-01-01", "2021-12-31"), 
                              products = "Sentinel-1")
records_filtered = records %>% filter(product_type == 'SLC')
```

```{r}
# descriptive stats on aoi filtered scenes
df = records_filtered %>% st_drop_geometry()

# convert relevant cols to factor
factor_cols = c("product",
                "product_type",
                "product_class",
                "platform",
                "platform_id",
                "sensor",
                "sensor_id",
                "sensor_mode",
                "polarisation_mode",
                "acquistion_type",
                "swath_id",
                "orbit_direction",
                "relativeorbit_number",
                "slice_number", 
                "timeliness")
df[factor_cols] = lapply(df[factor_cols], factor)

# convert download size to numerical value
df["size"] = map(df["size"], ~(strsplit(.x, " ")))[[1]] %>% 
  map_dbl(~as.numeric(.x[[1]]))

# filter relevant cols
df = df %>% 
  select(c(factor_cols, "size"))

# plot summary stats
skim(df)
```

```{r}
# built raster with coverage of scenes
polygons_scenes = as_Spatial(records_filtered$footprint) %>% 
                  spTransform(., crs(Aoi))
clip = gIntersection(polygons_scenes, Aoi, byid = TRUE, drop_lower_td = TRUE) %>% 
       SpatialPolygonsDataFrame(., as.data.frame(seq(1:length(.))), match.ID = F)
raster_empty = raster(ncol=5000, nrow=5000, crs = crs(clip))
extent(raster_empty) = extent(clip)
raster_scenes_count = fasterize(st_as_sf(clip), raster_empty, 'seq(1:length(.))', fun = 'count')
```

```{r}
# save distribution raster to disk
out_path = file.path(getwd(), "04_figures", "spatial_frequency_dist_scences")
writeRaster(raster_scenes_count, out_path, format='GTiff', overwrite = T)
```

```{r}
# built coverage raster with reduced resolution for quick plotting
raster_empty = raster(ncol=500, nrow=500, crs = crs(clip))
extent(raster_empty) = extent(clip)
plot_raster = fasterize(st_as_sf(clip), raster_empty, 'seq(1:length(.))', fun = 'count')

# write file as temp to disk & reload it into memory
# otherwise plotting via leaflet will mess up the projection
writeRaster(plot_raster, paste0(out_path, "_temp"), format='GTiff', overwrite = T)

plot_raster = raster(paste0(out_path, "_temp.tif"))
```

```{r}
# create grid of points as popup-markers for orbit info
grid = makegrid(Aoi, n=10000) %>% 
  SpatialPoints(proj4string = crs(Aoi)) %>% 
  spTransform(CRS("+init=epsg:4326"))

# retrieve orbit dirs & rel. orbits for the grid of points
records_orbits = records_filtered[c("orbit_direction", "relativeorbit_number")] %>% 
  transmute(orbit = paste0(substr(orbit_direction, 1,3), "_", relativeorbit_number)) %>% 
  as_Spatial()

orbits_intersect = over(grid, records_orbits, returnList = T)

orbits_formatted = map(.x = orbits_intersect, .f = ~toString(unique(.x)[["orbit"]])) %>% 
  map(.f=~str_replace_all(.x, ", ", "</br>"))

orbits_points = data.frame(
  lat = grid@coords[,2],
  lng = grid@coords[,1]
)

orbits_points1 = orbits_points %>% mutate(orbits = orbits_formatted)

# retrieve orbit number (including frame/slice number) for same number of points
records_orbits = as_Spatial(records_filtered["orbit_number"])

orbits_intersect = over(grid, records_orbits, returnList = T)

orbits_formatted = map(.x = orbits_intersect, .f = ~toString(unique(.x)[["orbit_number"]])) %>% 
  map(.f=~str_replace_all(.x, ", ", "</br>"))

orbits_points = data.frame(
  lat = grid@coords[,2],
  lng = grid@coords[,1]
)

orbits_points2 = orbits_points %>% mutate(orbits = orbits_formatted)
```

```{r}
# creating map plot
# color palette
colors_pal = colorNumeric(c("#FFFFCC", "#41B6C4","#0C2C84"), 
                          raster::values(plot_raster),
                          na.color = "transparent")

# function for decreasing legend  
addLegend_decreasing <- function (map, position = c("topright", "bottomright", "bottomleft","topleft"),
                                  pal, values, na.label = "NA", bins = 7, colors, 
                                  opacity = 0.5, labels = NULL, labFormat = labelFormat(), 
                                  title = NULL, className = "info legend", layerId = NULL, 
                                  group = NULL, data = getMapData(map), decreasing = FALSE) {
  
        position <- match.arg(position)
        type <- "unknown"
        na.color <- NULL
        extra <- NULL
        if (!missing(pal)) {
            if (!missing(colors)) 
                stop("You must provide either 'pal' or 'colors' (not both)")
            if (missing(title) && inherits(values, "formula")) 
                title <- deparse(values[[2]])
            values <- evalFormula(values, data)
            type <- attr(pal, "colorType", exact = TRUE)
            args <- attr(pal, "colorArgs", exact = TRUE)
            na.color <- args$na.color
            if (!is.null(na.color) && col2rgb(na.color, alpha = TRUE)[[4]] == 
                    0) {
                na.color <- NULL
            }
            if (type != "numeric" && !missing(bins)) 
                warning("'bins' is ignored because the palette type is not numeric")
            if (type == "numeric") {
                cuts <- if (length(bins) == 1) 
                    pretty(values, bins)
                else bins   
                if (length(bins) > 2) 
                    if (!all(abs(diff(bins, differences = 2)) <= 
                                     sqrt(.Machine$double.eps))) 
                        stop("The vector of breaks 'bins' must be equally spaced")
                n <- length(cuts)
                r <- range(values, na.rm = TRUE)
                cuts <- cuts[cuts >= r[1] & cuts <= r[2]]
                n <- length(cuts)
                p <- (cuts - r[1])/(r[2] - r[1])
                extra <- list(p_1 = p[1], p_n = p[n])
                p <- c("", paste0(100 * p, "%"), "")
                if (decreasing == TRUE){
                    colors <- pal(rev(c(r[1], cuts, r[2])))
                    labels <- rev(labFormat(type = "numeric", cuts))
                }else{
                    colors <- pal(c(r[1], cuts, r[2]))
                    labels <- rev(labFormat(type = "numeric", cuts))
                }
                colors <- paste(colors, p, sep = " ", collapse = ", ")
            }
            else if (type == "bin") {
                cuts <- args$bins
                n <- length(cuts)
                mids <- (cuts[-1] + cuts[-n])/2
                if (decreasing == TRUE){
                    colors <- pal(rev(mids))
                    labels <- rev(labFormat(type = "bin", cuts))
                }else{
                    colors <- pal(mids)
                    labels <- labFormat(type = "bin", cuts)
                }
            }
            else if (type == "quantile") {
                p <- args$probs
                n <- length(p)
                cuts <- quantile(values, probs = p, na.rm = TRUE)
                mids <- quantile(values, probs = (p[-1] + p[-n])/2, na.rm = TRUE)
                if (decreasing == TRUE){
                    colors <- pal(rev(mids))
                    labels <- rev(labFormat(type = "quantile", cuts, p))
                }else{
                    colors <- pal(mids)
                    labels <- labFormat(type = "quantile", cuts, p)
                }
            }
            else if (type == "factor") {
                v <- sort(unique(na.omit(values)))
                colors <- pal(v)
                labels <- labFormat(type = "factor", v)
                if (decreasing == TRUE){
                    colors <- pal(rev(v))
                    labels <- rev(labFormat(type = "factor", v))
                }else{
                    colors <- pal(v)
                    labels <- labFormat(type = "factor", v)
                }
            }
            else stop("Palette function not supported")
            if (!any(is.na(values))) 
                na.color <- NULL
        }
        else {
            if (length(colors) != length(labels)) 
                stop("'colors' and 'labels' must be of the same length")
        }
        legend <- list(colors = I(unname(colors)), labels = I(unname(labels)), 
                                     na_color = na.color, na_label = na.label, opacity = opacity, 
                                     position = position, type = type, title = title, extra = extra, 
                                     layerId = layerId, className = className, group = group)
        invokeMethod(map, data, "addLegend", legend)
                                  }

# map plot
leaflet::leaflet() %>% 
  leaflet::addTiles() %>%
  leaflet::addRasterImage(plot_raster, colors_pal, project=T, opacity = 0.8) %>%
  addLegend_decreasing(pal = colors_pal,
                       values = raster::values(plot_raster),
                       title = "SLC images 2021",
                       decreasing=T,
                       bins=10) %>% 
  addCircleMarkers(data = orbits_points1,
                   ~lng, 
                   ~lat,
                   opacity = 0,
                   fillOpacity = 0,
                   popup=unname(unlist(orbits_points1["orbits"])))
```

```{r}
# potential field selection via ArcGIS by intersecting the obtained spatial frequency distribution with a high density area of already analysed fields in the framework of sen2cube (upper austria)

# evaluate potential fields
potential_fields = file.path(getwd(), 
                             "01_data_raw",
                             "test_area_fields.geojson") %>% 
                   st_read()
                           
# frequency for crop types
freq_crops = potential_fields %>%
  st_drop_geometry() %>% 
  filter(SL_FLAECHE_BRUTTO_HA > 0.5) %>% 
  {table(.["SNAR_BEZEICHNUNG"])} %>% 
  as.data.frame() %>% 
  arrange(desc(Freq)) %>% 
  filter(Freq > 10)

# selected crop types
selected_crops = freq_crops %>% 
  top_n(5) %>% 
  pull(Var1) %>% 
  as.character()

# selected fields
fields = potential_fields %>% 
  filter(SL_FLAECHE_BRUTTO_HA > 0.5) %>% 
  filter(SNAR_BEZEICHNUNG %in% selected_crops)

#st_write(fields, file.path(getwd(), "01_data_raw", "fields.geojson"), delete_dsn = T)
```
```{r}
# some explorative analyses on selected fields
fields_nogeom = fields %>% st_drop_geometry

# a.) frequency of crop types
sort(table(fields_nogeom["SNAR_BEZEICHNUNG"]), decreasing=T)

# b.) distribution of sizes
fields_nogeom %>% 
  ggplot() +
  geom_violin(aes(x = factor(SNAR_BEZEICHNUNG),
                   y = SL_FLAECHE_BRUTTO_HA))
```



